/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Login': RouteRecordInfo<'Login', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'answer-components-list': RouteRecordInfo<'answer-components-list', '/Answer/Components/List', Record<never, never>, Record<never, never>>,
    'answer-components-modal-form': RouteRecordInfo<'answer-components-modal-form', '/Answer/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'answer-components-modal-list': RouteRecordInfo<'answer-components-modal-list', '/Answer/Components/ModalList', Record<never, never>, Record<never, never>>,
    'ForgotPassword': RouteRecordInfo<'ForgotPassword', '/ForgotPassword', Record<never, never>, Record<never, never>>,
    'ResetPassword': RouteRecordInfo<'ResetPassword', '/ResetPassword/:token', Record<never, never>, Record<never, never>>,
    'VerifyEmail': RouteRecordInfo<'VerifyEmail', '/VerifyEmail', Record<never, never>, Record<never, never>>,
    'Company-Form': RouteRecordInfo<'Company-Form', 'company-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Company-List': RouteRecordInfo<'Company-List', '/Company/List', Record<never, never>, Record<never, never>>,
    'dashboard-componentes-count-all-data': RouteRecordInfo<'dashboard-componentes-count-all-data', '/Dashboard/Componentes/CountAllData', Record<never, never>, Record<never, never>>,
    'dashboard-componentes-invoice-trend-chart': RouteRecordInfo<'dashboard-componentes-invoice-trend-chart', '/Dashboard/Componentes/InvoiceTrendChart', Record<never, never>, Record<never, never>>,
    'dashboard-componentes-status-distribution-chart': RouteRecordInfo<'dashboard-componentes-status-distribution-chart', '/Dashboard/Componentes/StatusDistributionChart', Record<never, never>, Record<never, never>>,
    'Entity-Form': RouteRecordInfo<'Entity-Form', 'entity-Form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Entity-List': RouteRecordInfo<'Entity-List', '/Entity/List', Record<never, never>, Record<never, never>>,
    'glosa-components-list': RouteRecordInfo<'glosa-components-list', '/Glosa/Components/List', Record<never, never>, Record<never, never>>,
    'glosa-components-modal-form': RouteRecordInfo<'glosa-components-modal-form', '/Glosa/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'glosa-components-modal-form-masive': RouteRecordInfo<'glosa-components-modal-form-masive', '/Glosa/Components/ModalFormMasive', Record<never, never>, Record<never, never>>,
    'glosa-components-modal-list': RouteRecordInfo<'glosa-components-modal-list', '/Glosa/Components/ModalList', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'invoice-components-data-type': RouteRecordInfo<'invoice-components-data-type', '/Invoice/Components/DataType', Record<never, never>, Record<never, never>>,
    'invoice-components-modal-errors-json': RouteRecordInfo<'invoice-components-modal-errors-json', '/Invoice/Components/ModalErrorsJson', Record<never, never>, Record<never, never>>,
    'invoice-components-modal-errors-xml': RouteRecordInfo<'invoice-components-modal-errors-xml', '/Invoice/Components/ModalErrorsXml', Record<never, never>, Record<never, never>>,
    'invoice-components-modal-upload-file-json': RouteRecordInfo<'invoice-components-modal-upload-file-json', '/Invoice/Components/ModalUploadFileJson', Record<never, never>, Record<never, never>>,
    'invoice-components-modal-upload-file-xml': RouteRecordInfo<'invoice-components-modal-upload-file-xml', '/Invoice/Components/ModalUploadFileXml', Record<never, never>, Record<never, never>>,
    'invoice-components-valid-jsonschema': RouteRecordInfo<'invoice-components-valid-jsonschema', '/Invoice/Components/ValidJSONSchema', Record<never, never>, Record<never, never>>,
    'Invoice-Form': RouteRecordInfo<'Invoice-Form', 'invoice-Form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Invoice-Furips1': RouteRecordInfo<'Invoice-Furips1', 'invoice-Furips1/:action/:invoice_id/:id?', Record<never, never>, Record<never, never>>,
    'Invoice-Furips2': RouteRecordInfo<'Invoice-Furips2', 'invoice-Furips2/:action/:invoice_id/:id?', Record<never, never>, Record<never, never>>,
    'Invoice-Furtran': RouteRecordInfo<'Invoice-Furtran', 'invoice-Furtran/:action/:invoice_id/:id?', Record<never, never>, Record<never, never>>,
    'Invoice-List': RouteRecordInfo<'Invoice-List', '/Invoice/List', Record<never, never>, Record<never, never>>,
    'invoice-payment-components-list': RouteRecordInfo<'invoice-payment-components-list', '/InvoicePayment/Components/List', Record<never, never>, Record<never, never>>,
    'invoice-payment-components-modal-form': RouteRecordInfo<'invoice-payment-components-modal-form', '/InvoicePayment/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'invoice-payment-components-modal-list': RouteRecordInfo<'invoice-payment-components-modal-list', '/InvoicePayment/Components/ModalList', Record<never, never>, Record<never, never>>,
    'patient-components-channels-channels-patient': RouteRecordInfo<'patient-components-channels-channels-patient', '/Patient/components/Channels/ChannelsPatient', Record<never, never>, Record<never, never>>,
    'patient-components-channels-channels-patient-modal-errors': RouteRecordInfo<'patient-components-channels-channels-patient-modal-errors', '/Patient/components/Channels/ChannelsPatientModalErrors', Record<never, never>, Record<never, never>>,
    'patient-components-channels-channels-patient-structure-modal-errors': RouteRecordInfo<'patient-components-channels-channels-patient-structure-modal-errors', '/Patient/components/Channels/ChannelsPatientStructureModalErrors', Record<never, never>, Record<never, never>>,
    'patient-components-modal-errors-patients': RouteRecordInfo<'patient-components-modal-errors-patients', '/Patient/components/ModalErrorsPatients', Record<never, never>, Record<never, never>>,
    'patient-components-modal-errors-patient-structure': RouteRecordInfo<'patient-components-modal-errors-patient-structure', '/Patient/components/ModalErrorsPatientStructure', Record<never, never>, Record<never, never>>,
    'patient-components-modal-form': RouteRecordInfo<'patient-components-modal-form', '/Patient/components/ModalForm', Record<never, never>, Record<never, never>>,
    'patient-components-modal-upload-patient-file-excel': RouteRecordInfo<'patient-components-modal-upload-patient-file-excel', '/Patient/components/ModalUploadPatientFileExcel', Record<never, never>, Record<never, never>>,
    'Patient-List': RouteRecordInfo<'Patient-List', '/Patient/List', Record<never, never>, Record<never, never>>,
    'Patient-Form': RouteRecordInfo<'Patient-Form', 'patient-Form/:action/:id?', Record<never, never>, Record<never, never>>,
    'redis-components-cache-hit-rate-chart': RouteRecordInfo<'redis-components-cache-hit-rate-chart', '/Redis/Components/CacheHitRateChart', Record<never, never>, Record<never, never>>,
    'redis-components-list-cache-keys': RouteRecordInfo<'redis-components-list-cache-keys', '/Redis/Components/ListCacheKeys', Record<never, never>, Record<never, never>>,
    'redis-components-list-tables': RouteRecordInfo<'redis-components-list-tables', '/Redis/Components/ListTables', Record<never, never>, Record<never, never>>,
    'redis-components-request-volume-chart': RouteRecordInfo<'redis-components-request-volume-chart', '/Redis/Components/RequestVolumeChart', Record<never, never>, Record<never, never>>,
    'redis-components-response-time-chart': RouteRecordInfo<'redis-components-response-time-chart', '/Redis/Components/ResponseTimeChart', Record<never, never>, Record<never, never>>,
    'Redis-Index': RouteRecordInfo<'Redis-Index', '/Redis/Index', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'service-components-data-urge-hos-born': RouteRecordInfo<'service-components-data-urge-hos-born', '/Service/Components/DataUrgeHosBorn', Record<never, never>, Record<never, never>>,
    'service-components-list': RouteRecordInfo<'service-components-list', '/Service/Components/List', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-hospitalization': RouteRecordInfo<'service-components-modal-form-hospitalization', '/Service/Components/ModalFormHospitalization', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-medical-consultation': RouteRecordInfo<'service-components-modal-form-medical-consultation', '/Service/Components/ModalFormMedicalConsultation', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-medicine': RouteRecordInfo<'service-components-modal-form-medicine', '/Service/Components/ModalFormMedicine', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-newly-born': RouteRecordInfo<'service-components-modal-form-newly-born', '/Service/Components/ModalFormNewlyBorn', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-other-service': RouteRecordInfo<'service-components-modal-form-other-service', '/Service/Components/ModalFormOtherService', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-procedure': RouteRecordInfo<'service-components-modal-form-procedure', '/Service/Components/ModalFormProcedure', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-service': RouteRecordInfo<'service-components-modal-form-service', '/Service/Components/ModalFormService', Record<never, never>, Record<never, never>>,
    'service-components-modal-form-urgency': RouteRecordInfo<'service-components-modal-form-urgency', '/Service/Components/ModalFormUrgency', Record<never, never>, Record<never, never>>,
    'ServiceVendor-List': RouteRecordInfo<'ServiceVendor-List', '/ServiceVendor/List', Record<never, never>, Record<never, never>>,
    'ServiceVendor-Form': RouteRecordInfo<'ServiceVendor-Form', 'serviceVendor-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'user-access-role-components-modal-form': RouteRecordInfo<'user-access-role-components-modal-form', '/UserAccess/Role/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'Role-List': RouteRecordInfo<'Role-List', '/UserAccess/Role/List', Record<never, never>, Record<never, never>>,
    'user-access-users-components-modal-form': RouteRecordInfo<'user-access-users-components-modal-form', '/UserAccess/Users/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'User-List': RouteRecordInfo<'User-List', '/UserAccess/Users/List', Record<never, never>, Record<never, never>>,
    'User-Profile': RouteRecordInfo<'User-Profile', '/UserAccess/Users/Profile', Record<never, never>, Record<never, never>>,
  }
}
