<?php

namespace Database\Seeders;

use App\Models\Servicio;
use Illuminate\Database\Seeder;

class ServicioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $arrayData = [
            ['id' => '1', 'codigo' => '105', 'nombre' => 'CUIDADO INTERMEDIO NEONATAL', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => null, 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '2', 'codigo' => '106', 'nombre' => 'CUIDADO INTERMEDIO PEDIATRICO', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '3', 'codigo' => '107', 'nombre' => 'CUIDADO INTERMEDIO ADULTOS', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '4', 'codigo' => '108', 'nombre' => 'CUIDADO INTENSIVO NEONATAL', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '5', 'codigo' => '109', 'nombre' => 'CUIDADO INTENSIVO PEDIATRICO', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '6', 'codigo' => '110', 'nombre' => 'CUIDADO INTENSIVO ADULTOS', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '7', 'codigo' => '1101', 'nombre' => 'ATENCION DEL PARTO', 'descripcion' => 'ATENCION INMEDIATA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '8', 'codigo' => '1102', 'nombre' => 'URGENCIAS', 'descripcion' => 'ATENCION INMEDIATA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '9', 'codigo' => '1103', 'nombre' => 'TRANSPORTE ASISTENCIAL BASICO', 'descripcion' => 'ATENCION INMEDIATA', 'habilitado' => 'NO', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '10', 'codigo' => '1104', 'nombre' => 'TRANSPORTE ASISTENCIAL MEDICALIZADO', 'descripcion' => 'ATENCION INMEDIATA', 'habilitado' => 'NO', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '11', 'codigo' => '1105', 'nombre' => 'ATENCION PREHOSPITALARIA', 'descripcion' => 'ATENCION INMEDIATA', 'habilitado' => 'NO', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '12', 'codigo' => '120', 'nombre' => 'CUIDADO BASICO NEONATAL', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '13', 'codigo' => '129', 'nombre' => 'HOSPITALIZACION ADULTOS', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'SI', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '14', 'codigo' => '130', 'nombre' => 'HOSPITALIZACION PEDIATRICA', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'SI', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '15', 'codigo' => '131', 'nombre' => 'HOSPITALIZACION EN SALUD MENTAL', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '16', 'codigo' => '132', 'nombre' => 'HOSPITALIZACION PARCIAL', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '17', 'codigo' => '133', 'nombre' => 'HOSPITALIZACION PACIENTE CRONICO CON VENTILADOR', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'SI', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '18', 'codigo' => '134', 'nombre' => 'HOSPITALIZACION PACIENTE CRONICO SIN VENTILADOR', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'SI', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '19', 'codigo' => '135', 'nombre' => 'HOSPITALIZACION EN  CONSUMO DE SUSTANCIAS PSICOACTIVAS', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '20', 'codigo' => '138', 'nombre' => 'CUIDADO BASICO DEL CONSUMO DE SUSTANCIAS PSICOACTIVAS', 'descripcion' => 'INTERNACION', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '21', 'codigo' => '201', 'nombre' => 'CIRUGIA DE CABEZA Y CUELLO', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '22', 'codigo' => '202', 'nombre' => 'CIRUGIA CARDIOVASCULAR', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '23', 'codigo' => '203', 'nombre' => 'CIRUGIA GENERAL', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '24', 'codigo' => '204', 'nombre' => 'CIRUGIA GINECOLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '25', 'codigo' => '205', 'nombre' => 'CIRUGIA MAXILOFACIAL', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '26', 'codigo' => '207', 'nombre' => 'CIRUGIA ORTOPEDICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '27', 'codigo' => '208', 'nombre' => 'CIRUGIA OFTALMOLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '28', 'codigo' => '209', 'nombre' => 'CIRUGIA OTORRINOLARINGOLOGIA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '29', 'codigo' => '210', 'nombre' => 'CIRUGIA ONCOLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '30', 'codigo' => '211', 'nombre' => 'CIRUGIA ORAL', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '31', 'codigo' => '212', 'nombre' => 'CIRUGIA PEDIATRICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '32', 'codigo' => '213', 'nombre' => 'CIRUGIA PLASTICA Y ESTETICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '33', 'codigo' => '214', 'nombre' => 'CIRUGIA VASCULAR Y ANGIOLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '34', 'codigo' => '215', 'nombre' => 'CIRUGIA UROLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '35', 'codigo' => '217', 'nombre' => 'OTRAS CIRUGIAS', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '36', 'codigo' => '218', 'nombre' => 'CIRUGIA ENDOVASCULAR NEUROLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '37', 'codigo' => '227', 'nombre' => 'CIRUGIA ONCOLOGICA PEDIATRICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '38', 'codigo' => '231', 'nombre' => 'CIRUGIA DE LA MANO', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '39', 'codigo' => '232', 'nombre' => 'CIRUGIA DE MAMA Y TUMORES TEJIDOS BLANDOS', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '40', 'codigo' => '233', 'nombre' => 'CIRUGIA DERMATOLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '41', 'codigo' => '234', 'nombre' => 'CIRUGIA DE TORAX', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '42', 'codigo' => '235', 'nombre' => 'CIRUGIA GASTROINTESTINAL', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '43', 'codigo' => '237', 'nombre' => 'CIRUGIA PLASTICA ONCOLOGICA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '44', 'codigo' => '245', 'nombre' => 'NEUROCIRUGIA', 'descripcion' => 'QUIRURGICOS', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '45', 'codigo' => '301', 'nombre' => 'ANESTESIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '46', 'codigo' => '302', 'nombre' => 'CARDIOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '47', 'codigo' => '303', 'nombre' => 'CIRUGIA CARDIOVASCULAR', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '48', 'codigo' => '304', 'nombre' => 'CIRUGIA GENERAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '49', 'codigo' => '306', 'nombre' => 'CIRUGIA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '50', 'codigo' => '308', 'nombre' => 'DERMATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '51', 'codigo' => '309', 'nombre' => 'DOLOR Y CUIDADOS PALIATIVOS', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '52', 'codigo' => '310', 'nombre' => 'ENDOCRINOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '53', 'codigo' => '311', 'nombre' => 'ENDODONCIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '54', 'codigo' => '312', 'nombre' => 'ENFERMERIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '55', 'codigo' => '313', 'nombre' => 'ESTOMATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '56', 'codigo' => '316', 'nombre' => 'GASTROENTEROLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '57', 'codigo' => '317', 'nombre' => 'GENETICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '58', 'codigo' => '318', 'nombre' => 'GERIATRIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '59', 'codigo' => '320', 'nombre' => 'GINECOBSTETRICIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '60', 'codigo' => '321', 'nombre' => 'HEMATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '61', 'codigo' => '323', 'nombre' => 'INFECTOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '62', 'codigo' => '324', 'nombre' => 'INMUNOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '63', 'codigo' => '325', 'nombre' => 'MEDICINA FAMILIAR', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '64', 'codigo' => '326', 'nombre' => 'MEDICINA FISICA Y DEL DEPORTE', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '65', 'codigo' => '327', 'nombre' => 'MEDICINA FISICA Y REHABILITACION', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '66', 'codigo' => '328', 'nombre' => 'MEDICINA GENERAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '67', 'codigo' => '329', 'nombre' => 'MEDICINA INTERNA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '68', 'codigo' => '330', 'nombre' => 'NEFROLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '69', 'codigo' => '331', 'nombre' => 'NEUMOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '70', 'codigo' => '332', 'nombre' => 'NEUROLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '71', 'codigo' => '333', 'nombre' => 'NUTRICION Y DIETETICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '72', 'codigo' => '334', 'nombre' => 'ODONTOLOGIA GENERAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '73', 'codigo' => '335', 'nombre' => 'OFTALMOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '74', 'codigo' => '336', 'nombre' => 'ONCOLOGIA CLINICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '75', 'codigo' => '337', 'nombre' => 'OPTOMETRIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '76', 'codigo' => '338', 'nombre' => 'ORTODONCIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '77', 'codigo' => '339', 'nombre' => 'ORTOPEDIA Y/O TRAUMATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '78', 'codigo' => '340', 'nombre' => 'OTORRINOLARINGOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '79', 'codigo' => '342', 'nombre' => 'PEDIATRIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '80', 'codigo' => '343', 'nombre' => 'PERIODONCIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '81', 'codigo' => '344', 'nombre' => 'PSICOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '82', 'codigo' => '345', 'nombre' => 'PSIQUIATRIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '83', 'codigo' => '346', 'nombre' => 'REHABILITACION ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '84', 'codigo' => '347', 'nombre' => 'REHABILITACION ORAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '85', 'codigo' => '348', 'nombre' => 'REUMATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '86', 'codigo' => '354', 'nombre' => 'TOXICOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '87', 'codigo' => '355', 'nombre' => 'UROLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '88', 'codigo' => '356', 'nombre' => 'OTRAS CONSULTAS DE ESPECIALIDAD', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '89', 'codigo' => '361', 'nombre' => 'CARDIOLOGIA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '90', 'codigo' => '362', 'nombre' => 'CIRUGIA DE CABEZA Y CUELLO', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '91', 'codigo' => '363', 'nombre' => 'CIRUGIA DE MANO', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '92', 'codigo' => '364', 'nombre' => 'CIRUGIA DE MAMA Y TUMORES TEJIDOS BLANDOS', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '93', 'codigo' => '365', 'nombre' => 'CIRUGIA DERMATOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '94', 'codigo' => '366', 'nombre' => 'CIRUGIA DE TORAX', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '95', 'codigo' => '367', 'nombre' => 'CIRUGIA GASTROINTESTINAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '96', 'codigo' => '368', 'nombre' => 'CIRUGIA GINECOLOGICA LAPAROSCOPICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '97', 'codigo' => '369', 'nombre' => 'CIRUGIA PLASTICA Y ESTETICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '98', 'codigo' => '370', 'nombre' => 'CIRUGIA PLASTICA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '99', 'codigo' => '371', 'nombre' => 'OTRAS CONSULTAS GENERALES', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '100', 'codigo' => '372', 'nombre' => 'CIRUGIA VASCULAR', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '101', 'codigo' => '373', 'nombre' => 'CIRUGIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '102', 'codigo' => '374', 'nombre' => 'CIRUGIA ONCOLOGICA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '103', 'codigo' => '375', 'nombre' => 'DERMATOLOGIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '104', 'codigo' => '377', 'nombre' => 'COLOPROCTOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '105', 'codigo' => '379', 'nombre' => 'GINECOLOGIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '106', 'codigo' => '383', 'nombre' => 'MEDICINA NUCLEAR', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '107', 'codigo' => '384', 'nombre' => 'NEFROLOGIA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '108', 'codigo' => '385', 'nombre' => 'NEONATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '109', 'codigo' => '386', 'nombre' => 'NEUMOLOGIA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '110', 'codigo' => '387', 'nombre' => 'NEUROCIRUGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '111', 'codigo' => '388', 'nombre' => 'NEUROPEDIATRIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '112', 'codigo' => '390', 'nombre' => 'OFTALMOLOGIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '113', 'codigo' => '391', 'nombre' => 'ONCOLOGIA Y HEMATOLOGIA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '114', 'codigo' => '393', 'nombre' => 'ORTOPEDIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '115', 'codigo' => '395', 'nombre' => 'UROLOGIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '116', 'codigo' => '396', 'nombre' => 'ODONTOPEDIATRIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '117', 'codigo' => '397', 'nombre' => 'MEDICINA ESTETICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '118', 'codigo' => '406', 'nombre' => 'HEMATOLOGIA ONCOLOGICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '119', 'codigo' => '407', 'nombre' => 'MEDICINA DEL TRABAJO Y MEDICINA LABORAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '120', 'codigo' => '408', 'nombre' => 'RADIOTERAPIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '121', 'codigo' => '409', 'nombre' => 'ORTOPEDIA PEDIATRICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '122', 'codigo' => '410', 'nombre' => 'CIRUGIA ORAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '123', 'codigo' => '411', 'nombre' => 'CIRUGIA MAXILOFACIAL', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '124', 'codigo' => '412', 'nombre' => 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - HOMEOPATICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '125', 'codigo' => '413', 'nombre' => 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - AYURVEDICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '126', 'codigo' => '414', 'nombre' => 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - TRADICIONAL CHINA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '127', 'codigo' => '415', 'nombre' => 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - NATUROPATICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '128', 'codigo' => '416', 'nombre' => 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - NEURALTERAPEUTICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '129', 'codigo' => '417', 'nombre' => 'TERAPIAS ALTERNATIVAS Y COMPLEMENTARIAS - BIOENERGETICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '130', 'codigo' => '418', 'nombre' => 'TERAPIAS ALTERNATIVAS Y COMPLEMENTARIAS - TERAPIA  CON FILTROS', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '131', 'codigo' => '419', 'nombre' => 'TERAPIAS ALTERNATIVAS Y COMPLEMENTARIAS - TERAPIAS  MANUALES', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '132', 'codigo' => '420', 'nombre' => 'VACUNACION', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'NO', 'extra_VI' => 'NO', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'NO', 'extra_X' => 'NO', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '133', 'codigo' => '421', 'nombre' => 'PATOLOGIA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '134', 'codigo' => '422', 'nombre' => 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - OSTEOPATICA', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '135', 'codigo' => '423', 'nombre' => 'SEGURIDAD Y SALUD EN EL TRABAJO', 'descripcion' => 'CONSULTA EXTERNA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '136', 'codigo' => '706', 'nombre' => 'LABORATORIO CLINICO', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '137', 'codigo' => '709', 'nombre' => 'QUIMIOTERAPIA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '138', 'codigo' => '711', 'nombre' => 'RADIOTERAPIA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '139', 'codigo' => '712', 'nombre' => 'TOMA DE MUESTRAS DE LABORATORIO CLINICO', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'NO', 'extra_VI' => 'NO', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'NO', 'extra_X' => 'NO', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '140', 'codigo' => '714', 'nombre' => 'SERVICIO FARMACEUTICO', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'SI', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '141', 'codigo' => '715', 'nombre' => 'MEDICINA NUCLEAR', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '142', 'codigo' => '717', 'nombre' => 'LABORATORIO CITOLOGIAS CERVICO-UTERINAS', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '143', 'codigo' => '728', 'nombre' => 'TERAPIA OCUPACIONAL', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '144', 'codigo' => '729', 'nombre' => 'TERAPIA RESPIRATORIA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '145', 'codigo' => '731', 'nombre' => 'LABORATORIO DE HISTOTECNOLOGIA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'NO', 'extra_VI' => 'NO', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'NO', 'extra_X' => 'NO', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '146', 'codigo' => '733', 'nombre' => 'HEMODIALISIS', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '147', 'codigo' => '734', 'nombre' => 'DIALISIS PERITONEAL', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '148', 'codigo' => '739', 'nombre' => 'FISIOTERAPIA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '149', 'codigo' => '740', 'nombre' => 'FONOAUDIOLOGIA Y/O TERAPIA DEL LENGUAJE', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'SI', 'extra_VIII' => 'SI', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '150', 'codigo' => '742', 'nombre' => 'DIAGNOSTICO VASCULAR', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '151', 'codigo' => '743', 'nombre' => 'HEMODINAMIA E INTERVENCIONISMO', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '152', 'codigo' => '744', 'nombre' => 'IMAGENES DIAGNOSTICAS- IONIZANTES', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '153', 'codigo' => '745', 'nombre' => 'IMAGENES DIAGNOSTICAS - NO IONIZANTES', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'SI', 'extra_IV' => 'SI', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '154', 'codigo' => '746', 'nombre' => 'GESTION PRE-TRANSFUSIONAL', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'NO', 'extra_VI' => 'NO', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'NO', 'extra_X' => 'NO', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '155', 'codigo' => '747', 'nombre' => 'PATOLOGIA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'NO', 'extra_II' => 'NO', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '156', 'codigo' => '748', 'nombre' => 'RADIOLOGIA ODONTOLOGICA', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'NO', 'extra_V' => 'SI', 'extra_VI' => 'SI', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'SI', 'extra_X' => 'SI', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
            ['id' => '157', 'codigo' => '749', 'nombre' => 'TOMA DE MUESTRAS DE CUELLO UTERINO Y GINECOLOGICAS', 'descripcion' => 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA', 'habilitado' => 'SI', 'aplicacion' => null, 'isStandardGEL' => 'False', 'isStandardMSPS' => 'False', 'extra_I' => 'SI', 'extra_II' => 'SI', 'extra_III' => 'NO', 'extra_IV' => 'SI', 'extra_V' => 'NO', 'extra_VI' => 'NO', 'extra_VII' => 'NO', 'extra_VIII' => 'NO', 'extra_IX' => 'NO', 'extra_X' => 'NO', 'valorRegistro' => null, 'usuarioResponsable' => null, 'fecha_actualizacion' => '2022-09-02 11:06:33 AM', 'isPublicPrivate' => null],
        ];

        // Inicializar la barra de progreso
        $this->command->info('Starting Seed Data ...');
        $bar = $this->command->getOutput()->createProgressBar(count($arrayData));

        foreach ($arrayData as $key => $value) {
            $data = new Servicio;
            $data->codigo = $value['codigo'];
            $data->nombre = $value['nombre'];
            $data->descripcion = $value['descripcion'];
            $data->habilitado = $value['habilitado'];
            $data->aplicacion = $value['aplicacion'];
            $data->isStandardGEL = $value['isStandardGEL'];
            $data->isStandardMSPS = $value['isStandardMSPS'];
            $data->extra_I = $value['extra_I'];
            $data->extra_II = $value['extra_II'];
            $data->extra_III = $value['extra_III'];
            $data->extra_IV = $value['extra_IV'];
            $data->extra_V = $value['extra_V'];
            $data->extra_VI = $value['extra_VI'];
            $data->extra_VII = $value['extra_VII'];
            $data->extra_VIII = $value['extra_VIII'];
            $data->extra_IX = $value['extra_IX'];
            $data->extra_X = $value['extra_X'];
            $data->valorRegistro = $value['valorRegistro'];
            $data->usuarioResponsable = $value['usuarioResponsable'];
            $data->fecha_actualizacion = $value['fecha_actualizacion'];
            $data->isPublicPrivate = $value['isPublicPrivate'];

            $data->save();
            $bar->advance();
        }
        $bar->finish(); // Finalizar la barra
    }
}
